### ISSUE TITLE
Handle Connection header

### ISSUE THREAD

**Issue by hhkim0729** [srngch/ngin-xs#47]
- 요청에 `Connection: close` 헤더가 있으면 응답을 보낸 후 연결 끊기

**Comment by srngch** [comment]
1. Worker의 send 메소드 안에서 send 하고 난 다음
2. Connection: close 헤더를 체크하고
3. close의 경우 FT_FALSE를 리턴한다
4. 3에서 받은 내용을 그대로 Worker의 work 메소드가 리턴하게 만든다
  - FT_FALSE 인 경우 Worker 인스턴스가 정리되면서 연결이 종료된다 `Master.cpp:107`
