### ISSUE TITLE
Refactor entire code

### ISSUE THREAD

**Issue by srngch** [srngch/ngin-xs#67]
중간 리팩토링
- [x] 컨테이너 타입, 이터레이터에 대한 typedef
- [x] 예외 메시지 통일 (`함수이름: 오류메시지`)
- [x] 헤더 인클루드 정리
- [x] 함수 정리
- [x] 파일 구조 정리

**Comment by hhkim0729** [comment]
1. 컨테이너 타입, 이터레이터에 대한 typedef
2. 예외 메시지 통일 (`함수이름: 오류메시지`)
